FROM node:alpine:13.12.0-alpine

WORKDIR '/src/react-client'

ENV PATH /src/react-client/node_modules/.bin:$PATH

COPY ./package.json ./

RUN npm install

COPY . .

EXPOSE 3010

CMD ["npm" ,"run", "start"]